language: csharp
solution: here-webapi.sln

git:
 depth: 10

dotnet: 2.2.402
mono: none
env:
 global:
   - CONFIGURATION: Release
   - DOTNET_CLI_TELEMETRY_OPTOUT: 1
   - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
   - NET_CORE_VERSION: netcoreapp2.2
before_script:
 - |
   set -eu
   dotnet --info
   set +u
script:
 - |
   set -eu
 - dotnet build -c "$CONFIGURATION" /nologo
 - dotnet restore here-webapi
 - dotnet publish here-webapi -c "$CONFIGURATION" -r "win-x64" --no-restore /nologo 
 wait
 set +u
 
 matrix:
  allow_failures:
    - os: windows
fast_finish:true