version: 2.1
orbs:
    win: circleci/windows@1.0.0
jobs:
    build:
        executor:
            name: win/vs2019
            shell: powershell.executor
           
        steps:
            - checkout
            - restore_cache:
                keys:
            - run:
                name: Restore Packages
                command: dotnet.exe restore
            - save_cache:
                paths:
                    - C:\Users\circleci\.nuget\packages
            - run:
                name: Release & Publish API
                command: dotnet.exe publish  -c "Release" -r win10-x64
            - store_artifacts:
                path: .\bin\Release\netcoreapp2.2\win10-x64\publish\here-webapi.dll